import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { GraphQLClient, gql } from "graphql-request";
import BlogCard from "../components/BlogCard";

const graphcms = new GraphQLClient(
  "https://api-ap-northeast-1.graphcms.com/v2/cl496hyz30x2v01wdga9ociv5/master"
);

const QUERY = gql`
  {
    posts {
      id
      title
      date
      slug
      content {
        html
      }
      author {
        name
        avator {
          url
        }
      }
      photo {
        createdBy {
          id
        }
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.jsブログ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.title}>
          <h2>Next.jsとGraphQLブログ</h2>
        </div>
        <div className={styles.gridWrapper}>
          {posts.map((post) => (
            <BlogCard
              title={post.title}
              author={post.author}
              photo={post.photo}
              date={post.date}
              slug={post.slug}
              key={post.id}
            />
          ))}
        </div>
      </main>
    </div>
  );
}
